version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - exhaustive
    - gocritic
    - gosec
    - misspell
    - noctx
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    gosec:
      excludes:
        - G104
    govet:
      enable-all: true
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: range
        - name: receiver-naming
        - name: indent-error-flow
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
        - name: redefines-builtin-id
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocritic
          - gosec
          - revive
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/github-builder/container-orchestrator
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
